### ISSUE TITLE
Pods in StatefulSets(Redis) cannot resolve each other by expected hostnames

### ISSUE THREAD

**Issue by tangcong** [tangcong/codis-operator#3]
rt

**Comment by tangcong** [comment]
https://github.com/kubernetes/kubernetes/issues/45779

**Comment by AlexProfi** [comment]
What version of kubernetes have fixed it? I used 1.11.5 And it works correct when I set
redis-cluster-1.redis-cluster.default.svc.cluster.local
with redis-cluster-1 it doesn't work
